apiVersion: v1
kind: Service
metadata:
  name: payroll-app
  namespace: ${K8S_NAMESPACE}
  labels:
    app: payroll-app
spec:
  type: LoadBalancer
  selector:
    app: payroll-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
